import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'

async function studyState(page: Page) {
  const [, id, version] = new URL(page.url()).hash.slice(1).split('/')
  return (await page.request.get(`/api/state?set_id=${encodeURIComponent(id)}&version=${version}`)).json()
}

const password = 'browser-test-passphrase-123'
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Identifiant', { exact: true }).fill('browser_oli')
  await page.getByLabel('Mot de passe', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Retrouver mes cartes' }).click()
  await expect(page.getByRole('heading', { name: 'Mes ensembles.' })).toBeVisible()
  await expect(page.locator('.collection-topbar')).toHaveCount(0)
})

test('create, study, edit and resume an earlier version with its progress', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.getByRole('button', { name: 'Nouvel ensemble' }).click()
  await page.getByLabel('Titre de l’ensemble', { exact: true }).fill('Mon ensemble navigateur')
  await page.getByLabel('Terme 1', { exact: true }).fill('Première question')
  await page.getByLabel('Définition 1', { exact: true }).fill('Première réponse')
  await page.getByRole('button', { name: 'Ajouter une carte' }).click()
  await page.getByLabel('Terme 2', { exact: true }).fill('Deuxième question')
  await page.getByLabel('Définition 2', { exact: true }).fill('Deuxième réponse')
  await page.getByRole('button', { name: 'Créer l’ensemble', exact: true }).first().click()
  await page.getByRole('button', { name: 'Étudier cet ensemble', exact: true }).click()
  await expect(page.locator('.sidebar-deck h3')).toHaveText('Mon ensemble navigateur')
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect.poll(async () => (await studyState(page)).correct).toBe(1)
  await page.reload()
  await expect.poll(async () => (await studyState(page)).correct).toBe(1)
  await page.locator('.sidebar').getByRole('button', { name: 'Voir l’ensemble', exact: true }).click()
  await page.getByRole('textbox', { name: 'Définition 1', exact: true }).fill('Réponse modifiée')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('button', { name: 'Étudier cet ensemble', exact: true }).click()
  await expect(page.locator('.cover-index')).toHaveText('VERSION 2')
  expect((await studyState(page)).correct).toBe(0)
  await page.locator('.sidebar').getByRole('button', { name: 'Voir l’ensemble', exact: true }).click()
  await page.getByLabel('Version de Mon ensemble navigateur', { exact: true }).selectOption('1')
  await page.getByRole('button', { name: 'Étudier cet ensemble', exact: true }).click()
  await expect(page.locator('.cover-index')).toHaveText('VERSION 1')
  await expect.poll(async () => (await studyState(page)).correct).toBe(1)

  const other = await context.browser()!.newContext()
  const max = await other.newPage()
  await max.goto('http://127.0.0.1:8885/')
  await max.getByLabel('Identifiant', { exact: true }).fill('browser_max')
  await max.getByLabel('Mot de passe', { exact: true }).fill(password)
  await max.getByRole('button', { name: 'Retrouver mes cartes' }).click()
  await expect(max.getByRole('heading', { name: 'Mes ensembles.' })).toBeVisible()
  await expect(max.getByRole('heading', { name: 'Mon ensemble navigateur', exact: true })).toHaveCount(0)
  await expect(max.getByRole('heading', { name: 'Éthique de l’ingénieur', exact: true })).toBeVisible()
  expect(errors).toEqual([])
  await other.close()
})

test('mobile editor, card removal and duplicate validation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.getByRole('button', { name: 'Nouvel ensemble' }).click()
  await page.getByLabel('Titre de l’ensemble', { exact: true }).fill('Validation mobile')
  await page.getByLabel('Terme 1', { exact: true }).fill('Identique')
  await page.getByLabel('Définition 1', { exact: true }).fill('Identique')
  await page.getByRole('button', { name: 'Ajouter une carte' }).click()
  await page.getByLabel('Terme 2', { exact: true }).fill('Identique')
  await page.getByLabel('Définition 2', { exact: true }).fill('Identique')
  await page.getByRole('button', { name: 'Créer l’ensemble', exact: true }).first().click()
  await expect(page.getByRole('alert')).toContainText('identiques')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Supprimer la carte 2' }).click()
  await expect(page.getByLabel('Terme 2', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Créer l’ensemble', exact: true }).first().click()
  await expect(page.locator('.version-badge')).toHaveText('Version 1')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const sidebar = page.locator('.collection-sidebar')
  await expect(sidebar.getByRole('button', { name: 'Changer mon mot de passe' })).toBeVisible()
  await sidebar.getByRole('button', { name: 'Se déconnecter' }).click()
  await expect(page.getByLabel('Identifiant', { exact: true })).toBeVisible()
})
