import { test, expect } from '@playwright/test'

const password = 'browser-test-passphrase-123'
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Identifiant', { exact: true }).fill('browser_oli')
  await page.getByLabel('Mot de passe', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Retrouver mes cartes' }).click()
  await expect(page.getByRole('heading', { name: 'Le savoir se cultive.' })).toBeVisible()
  await page.getByRole('button', { name: 'Mes ensembles', exact: true }).click()
})

test('create, study, edit and resume an earlier version with its progress', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.getByRole('button', { name: 'Nouvel ensemble' }).click()
  await page.getByLabel('Titre de l’ensemble', { exact: true }).fill('Mon ensemble navigateur')
  await page.getByLabel('Question 1', { exact: true }).fill('Première question')
  await page.getByLabel('Réponse 1', { exact: true }).fill('Première réponse')
  await page.getByRole('button', { name: 'Ajouter une carte' }).click()
  await page.getByLabel('Question 2', { exact: true }).fill('Deuxième question')
  await page.getByLabel('Réponse 2', { exact: true }).fill('Deuxième réponse')
  await page.getByRole('button', { name: 'Enregistrer l’ensemble' }).click()
  await expect(page.locator('.sidebar-deck h3')).toHaveText('Mon ensemble navigateur')
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect(page.locator('.session-summary')).toContainText('1')
  await page.reload()
  await expect(page.locator('.session-summary')).toContainText('1')
  await page.getByRole('button', { name: 'Mes ensembles', exact: true }).click()
  await page.getByRole('button', { name: 'Modifier Mon ensemble navigateur', exact: true }).click()
  await page.getByRole('textbox', { name: 'Réponse 1', exact: true }).fill('Réponse modifiée')
  await page.getByRole('button', { name: 'Enregistrer l’ensemble' }).click()
  await expect(page.locator('.cover-index')).toHaveText('VERSION 2')
  await expect(page.locator('.session-summary > div').first()).toContainText('0')
  await page.getByRole('button', { name: 'Mes ensembles', exact: true }).click()
  await page.getByLabel('Version de Mon ensemble navigateur', { exact: true }).selectOption('1')
  await expect(page.locator('.cover-index')).toHaveText('VERSION 1')
  await expect(page.locator('.session-summary > div').first()).toContainText('1')

  const other = await context.browser()!.newContext()
  const max = await other.newPage()
  await max.goto('http://127.0.0.1:8885/')
  await max.getByLabel('Identifiant', { exact: true }).fill('browser_max')
  await max.getByLabel('Mot de passe', { exact: true }).fill(password)
  await max.getByRole('button', { name: 'Retrouver mes cartes' }).click()
  await max.getByRole('button', { name: 'Mes ensembles', exact: true }).click()
  await expect(max.getByRole('heading', { name: 'Mon ensemble navigateur', exact: true })).toHaveCount(0)
  await expect(max.getByRole('heading', { name: 'Éthique de l’ingénieur', exact: true })).toBeVisible()
  expect(errors).toEqual([])
  await other.close()
})

test('mobile editor, card removal and duplicate validation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.getByRole('button', { name: 'Nouvel ensemble' }).click()
  await page.getByLabel('Titre de l’ensemble', { exact: true }).fill('Validation mobile')
  await page.getByLabel('Question 1', { exact: true }).fill('Identique')
  await page.getByLabel('Réponse 1', { exact: true }).fill('Identique')
  await page.getByRole('button', { name: 'Ajouter une carte' }).click()
  await page.getByLabel('Question 2', { exact: true }).fill('Identique')
  await page.getByLabel('Réponse 2', { exact: true }).fill('Identique')
  await page.getByRole('button', { name: 'Enregistrer l’ensemble' }).click()
  await expect(page.getByRole('alert')).toContainText('identiques')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Supprimer la carte 2' }).click()
  await expect(page.getByLabel('Question 2', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Enregistrer l’ensemble' }).click()
  await expect(page.getByRole('heading', { name: 'Le savoir se cultive.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
