import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json()
  await request.post('/api/actions', { data: { type: 'reset', revision: state.revision } })
  const reset = await (await request.get('/api/state')).json()
  await request.post('/api/actions', { data: { type: 'settings', defaults: true, revision: reset.revision } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ouvrir Éthique de l’ingénieur', exact: true }).click()
  await page.getByRole('button', { name: 'Étudier cet ensemble', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Éthique de l’ingénieur', level: 1, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Révisions', exact: true })).toHaveCount(0)
  await expect(page.locator('.topbar')).toHaveCount(0)
})

test('reveal, keyboard grades, history and reload preserve the session', async ({ page, request }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeDisabled()
  const prompt = await page.getByRole('button', { name: 'Retourner la carte', exact: true }).innerText()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeEnabled()
  await page.keyboard.press('2')
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await expect(page.locator('.navigation-position')).toContainText('02')
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.history-message')).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Retourner la carte', exact: true })).toHaveText(prompt)
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.reload()
  expect((await (await request.get('/api/state')).json()).correct).toBe(1)
  expect(failures).toEqual([])
})

test('typed input keeps number, space and arrow keys, then shows feedback', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await page.getByRole('switch', { name: 'Réponse écrite' }).click()
  await expect(page.getByRole('switch', { name: 'Réponse écrite' })).toBeChecked()
  await page.getByRole('button', { name: 'Enregistrer les paramètres', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const input = page.getByLabel('Rappelle-toi la réponse, puis écris-la.')
  await input.fill('12 test')
  await input.press('ArrowLeft')
  await input.press('Space')
  await input.press('2')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  expect((await (await request.get('/api/state')).json()).wrong).toBe(0)
  await input.press('Enter')
  await expect(page.locator('.wrong-feedback')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continuer' })).toBeVisible()
  await page.keyboard.press('Space')
  expect((await (await request.get('/api/state')).json()).wrong).toBe(1)
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page.getByLabel('Rappelle-toi la réponse, puis écris-la.')).toBeVisible()
})

test('mobile layout, dialogs and focus mode work without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('switch', { name: 'Réponse écrite' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await page.getByRole('button', { name: 'Quitter le mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await page.screenshot({ path: '/tmp/quizlet-web-mobile.png', fullPage: true })
})

test('stale tab refreshes without double grading', async ({ page, context, request }) => {
  const other = await context.newPage()
  await other.goto('/#study/default-ethics/1')
  await expect(other.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await other.getByRole('button', { name: 'Révéler la réponse' }).click()
  await expect(other.getByRole('alert')).toContainText('autre onglet')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  await other.close()
})

test('reset asks in the app and updates the journey', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await page.getByRole('button', { name: 'Recommencer la progression', exact: true }).click()
  await page.getByRole('button', { name: 'Garder ma progression', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect((await (await request.get('/api/state')).json()).correct).toBe(1)
  await page.getByRole('button', { name: 'Recommencer la progression', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Une nouvelle page ?' })).toBeVisible()
  await page.getByRole('button', { name: 'Recommencer', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.navigation-position')).toContainText('01')
  const reset = await (await request.get('/api/state')).json()
  expect([reset.correct, reset.wrong, reset.streak, reset.progress, reset.initial_mastered, reset.final_mastered]).toEqual([0, 0, 0, 0, 0, 0])
  expect(reset.rounds[0].status).toBe('ACTIVE')
  expect(reset.rounds.slice(1).every((round: { status: string }) => round.status === 'LOCKED')).toBe(true)
  expect(reset.final_status).toBe('LOCKED')
  await page.reload()
  await expect(page.getByRole('progressbar', { name: 'Maîtrise globale' })).toHaveAttribute('aria-valuenow', '0')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  await page.screenshot({ path: '/tmp/quizlet-web-desktop.png', fullPage: true })
})


test('left panel opens help and the set view', async ({ page }) => {
  const sidebar = page.locator('.sidebar')
  await sidebar.getByRole('button', { name: 'Aide', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Apprendre, simplement.' })).toBeVisible()
  await page.keyboard.press('Escape')
  await sidebar.getByRole('button', { name: 'Voir l’ensemble', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Étudier cet ensemble', exact: true })).toBeVisible()
  await expect(page.locator('.collection-topbar')).toHaveCount(0)
  await page.locator('.collection-sidebar').getByRole('button', { name: 'Mes ensembles' }).click()
  await expect(page.getByRole('heading', { name: 'Mes ensembles.' })).toBeVisible()
})

test('completed learning offers restart without a revisions link', async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json()
  await page.route('**/api/state*', route => route.fulfill({ json: { ...state, complete: true, phase: 'COMPLETE', question: null, progress: 1 } }))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Tout est maîtrisé.' })).toBeVisible()
  await expect(page.getByRole('button', { name: /révision/i })).toHaveCount(0)
  await page.getByRole('button', { name: 'Recommencer l’apprentissage', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Une nouvelle page ?' })).toBeVisible()
})


test('learning configuration saves all settings, preserves answers and restores defaults', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await page.getByRole('button', { name: 'Mode concentration', exact: true }).click()
  await page.getByRole('button', { name: 'Configuration de l’apprentissage', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Configuration de l’apprentissage' })
  await dialog.getByLabel('Taille des groupes', { exact: true }).fill('5')
  await dialog.getByLabel('Réussites pour devenir familière', { exact: true }).fill('2')
  await dialog.getByLabel('Réussites pour devenir maîtrisée', { exact: true }).fill('6')
  await dialog.getByLabel('Score minimum de maîtrise (%)', { exact: true }).fill('90')
  await dialog.getByText('Espacement et priorités de sélection', { exact: true }).click()
  await dialog.getByLabel('Questions entre deux rappels', { exact: true }).fill('4')
  await dialog.getByLabel('Priorité des cartes en apprentissage', { exact: true }).fill('7')
  await dialog.getByLabel('Baisse du score après une erreur (%)', { exact: true }).fill('40')
  await dialog.getByRole('button', { name: 'Enregistrer les paramètres', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const saved = await (await request.get('/api/state')).json()
  expect(saved.config.round_size).toBe(5)
  expect(saved.config.familiar_after).toBe(2)
  expect(saved.config.minimum_successful_recalls).toBe(6)
  expect(saved.config.mastery_threshold).toBe(.9)
  expect(saved.config.minimum_spacing_questions).toBe(4)
  expect(saved.config.weight_learning).toBe(7)
  expect(saved.config.incorrect_answer_penalty).toBe(.4)
  expect(saved.correct).toBe(1)
  expect(saved.rounds[0].total).toBe(5)
  await page.reload()
  await page.getByRole('button', { name: 'Configuration de l’apprentissage', exact: true }).click()
  await expect(dialog.getByLabel('Taille des groupes', { exact: true })).toHaveValue('5')
  await dialog.getByLabel('Taille des groupes', { exact: true }).fill('0')
  await dialog.getByRole('button', { name: 'Enregistrer les paramètres', exact: true }).click()
  await expect(dialog).toBeVisible()
  expect((await (await request.get('/api/state')).json()).config.round_size).toBe(5)
  await dialog.getByRole('button', { name: 'Rétablir les paramètres par défaut', exact: true }).click()
  await expect(dialog.getByLabel('Taille des groupes', { exact: true })).toHaveValue('10')
  await dialog.getByRole('button', { name: 'Enregistrer les paramètres', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const restored = await (await request.get('/api/state')).json()
  expect(restored.config).toEqual(restored.default_config)
  expect(restored.correct).toBe(1)
})

test('configuration can be cancelled and remains usable on a narrow screen', async ({ page, request }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.getByRole('button', { name: 'Configuration de l’apprentissage', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Taille des groupes', { exact: true }).fill('7')
  await dialog.getByText('Espacement et priorités de sélection', { exact: true }).click()
  await page.screenshot({ path: '/tmp/memo-study-settings-mobile.png' })
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  expect((await (await request.get('/api/state')).json()).config.round_size).toBe(10)
  await page.getByRole('button', { name: 'Configuration de l’apprentissage', exact: true }).click()
  await expect(dialog.getByLabel('Taille des groupes', { exact: true })).toHaveValue('10')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})

test('multiple choice records a choice and keeps the flashcard fallback', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Configuration de l’apprentissage', exact: true }).click()
  await page.getByRole('switch', { name: 'Choix multiples', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer les paramètres', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.choice-answer')).toHaveCount(4)
  await page.locator('.choice-answer').first().click()
  await expect(page.locator('.feedback')).toBeVisible()
  const answered = await (await request.get('/api/state')).json()
  expect(answered.correct + answered.wrong).toBe(1)
  await page.getByRole('button', { name: 'Continuer' }).click()
  await page.getByRole('button', { name: 'Retourner la carte', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeEnabled()
})
