import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json()
  await request.post('/api/actions', { data: { type: 'reset', revision: state.revision } })
  const reset = await (await request.get('/api/state')).json()
  if (reset.typed_recall) await request.post('/api/actions', { data: { type: 'settings', typed: false, revision: reset.revision } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ouvrir Éthique de l’ingénieur', exact: true }).click()
  await page.getByRole('button', { name: 'Étudier cet ensemble', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Éthique de l’ingénieur', level: 1, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Révisions', exact: true })).toHaveCount(0)
  await expect(page.locator('.topbar')).toHaveCount(0)
})

test('reveal, keyboard grades, history and reload preserve the session', async ({ page, request }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeDisabled()
  const prompt = await page.getByRole('button', { name: 'Retourner la carte', exact: true }).innerText()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeEnabled()
  await page.keyboard.press('2')
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await expect(page.locator('.navigation-position')).toContainText('02')
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.history-message')).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Retourner la carte', exact: true })).toHaveText(prompt)
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.reload()
  expect((await (await request.get('/api/state')).json()).correct).toBe(1)
  expect(failures).toEqual([])
})

test('typed input keeps number, space and arrow keys, then shows feedback', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await page.getByRole('switch', { name: 'Réponse écrite' }).click()
  await expect(page.getByRole('switch')).toBeChecked()
  await page.getByRole('button', { name: 'Fermer', exact: true }).click()
  const input = page.getByLabel('Rappelle-toi la réponse, puis écris-la.')
  await input.fill('12 test')
  await input.press('ArrowLeft')
  await input.press('Space')
  await input.press('2')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  expect((await (await request.get('/api/state')).json()).wrong).toBe(0)
  await input.press('Enter')
  await expect(page.locator('.wrong-feedback')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continuer' })).toBeVisible()
  await page.keyboard.press('Space')
  expect((await (await request.get('/api/state')).json()).wrong).toBe(1)
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page.getByLabel('Rappelle-toi la réponse, puis écris-la.')).toBeVisible()
})

test('mobile layout, dialogs and focus mode work without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('switch', { name: 'Réponse écrite' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await page.getByRole('button', { name: 'Quitter le mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await page.screenshot({ path: '/tmp/quizlet-web-mobile.png', fullPage: true })
})

test('stale tab refreshes without double grading', async ({ page, context, request }) => {
  const other = await context.newPage()
  await other.goto('/#study/default-ethics/1')
  await expect(other.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await other.getByRole('button', { name: 'Révéler la réponse' }).click()
  await expect(other.getByRole('alert')).toContainText('autre onglet')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  await other.close()
})

test('reset asks in the app and updates the journey', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await page.getByRole('button', { name: 'Recommencer la progression', exact: true }).click()
  await page.getByRole('button', { name: 'Garder ma progression', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect((await (await request.get('/api/state')).json()).correct).toBe(1)
  await page.getByRole('button', { name: 'Recommencer la progression', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Une nouvelle page ?' })).toBeVisible()
  await page.getByRole('button', { name: 'Recommencer', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.navigation-position')).toContainText('01')
  const reset = await (await request.get('/api/state')).json()
  expect([reset.correct, reset.wrong, reset.streak, reset.progress, reset.initial_mastered, reset.final_mastered]).toEqual([0, 0, 0, 0, 0, 0])
  expect(reset.rounds[0].status).toBe('ACTIVE')
  expect(reset.rounds.slice(1).every((round: { status: string }) => round.status === 'LOCKED')).toBe(true)
  expect(reset.final_status).toBe('LOCKED')
  await page.reload()
  await expect(page.getByRole('progressbar', { name: 'Maîtrise globale' })).toHaveAttribute('aria-valuenow', '0')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  await page.screenshot({ path: '/tmp/quizlet-web-desktop.png', fullPage: true })
})


test('left panel opens help and the set view', async ({ page }) => {
  const sidebar = page.locator('.sidebar')
  await sidebar.getByRole('button', { name: 'Aide', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Apprendre, simplement.' })).toBeVisible()
  await page.keyboard.press('Escape')
  await sidebar.getByRole('button', { name: 'Voir l’ensemble', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Étudier cet ensemble', exact: true })).toBeVisible()
  await expect(page.locator('.collection-topbar')).toHaveCount(0)
  await page.locator('.collection-sidebar').getByRole('button', { name: 'Mes ensembles' }).click()
  await expect(page.getByRole('heading', { name: 'Mes ensembles.' })).toBeVisible()
})

test('completed learning offers restart without a revisions link', async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json()
  await page.route('**/api/state*', route => route.fulfill({ json: { ...state, complete: true, phase: 'COMPLETE', question: null, progress: 1 } }))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Tout est maîtrisé.' })).toBeVisible()
  await expect(page.getByRole('button', { name: /révision/i })).toHaveCount(0)
  await page.getByRole('button', { name: 'Recommencer l’apprentissage', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Une nouvelle page ?' })).toBeVisible()
})
