import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json()
  await request.post('/api/actions', { data: { type: 'reset', revision: state.revision } })
  const reset = await (await request.get('/api/state')).json()
  if (reset.typed_recall) await request.post('/api/actions', { data: { type: 'settings', typed: false, revision: reset.revision } })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Le savoir se cultive.' })).toBeVisible()
})

test('reveal, keyboard grades, history and reload preserve the session', async ({ page, request }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeDisabled()
  const prompt = await page.getByRole('button', { name: 'Retourner la carte', exact: true }).innerText()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Bien retenu' })).toBeEnabled()
  await page.keyboard.press('2')
  await expect.poll(async () => (await (await request.get('/api/state')).json()).correct).toBe(1)
  await expect(page.locator('.navigation-position')).toContainText('02')
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.history-message')).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Retourner la carte', exact: true })).toHaveText(prompt)
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.reload()
  await expect(page.locator('.session-summary')).toContainText('1')
  expect((await (await request.get('/api/state')).json()).correct).toBe(1)
  expect(failures).toEqual([])
})

test('typed input keeps number, space and arrow keys, then shows feedback', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await page.getByRole('switch', { name: 'Réponse écrite' }).click()
  await expect(page.getByRole('switch')).toBeChecked()
  await page.getByRole('button', { name: 'Fermer', exact: true }).click()
  const input = page.getByLabel('Rappelle-toi la réponse, puis écris-la.')
  await input.fill('12 test')
  await input.press('ArrowLeft')
  await input.press('Space')
  await input.press('2')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  expect((await (await request.get('/api/state')).json()).wrong).toBe(0)
  await input.press('Enter')
  await expect(page.locator('.wrong-feedback')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continuer' })).toBeVisible()
  await page.keyboard.press('Space')
  expect((await (await request.get('/api/state')).json()).wrong).toBe(1)
  await page.getByRole('button', { name: 'Continuer' }).click()
  await expect(page.getByLabel('Rappelle-toi la réponse, puis écris-la.')).toBeVisible()
})

test('mobile layout, dialogs and focus mode work without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Les cartes du groupe' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.group-cards li')).toHaveCount(10)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await page.getByRole('button', { name: 'Quitter le mode concentration', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await page.screenshot({ path: '/tmp/quizlet-web-mobile.png', fullPage: true })
})

test('stale tab refreshes without double grading', async ({ page, context, request }) => {
  const other = await context.newPage()
  await other.goto('/')
  await expect(other.getByRole('button', { name: 'Révéler la réponse' })).toBeVisible()
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await other.getByRole('button', { name: 'Révéler la réponse' }).click()
  await expect(other.getByRole('alert')).toContainText('autre onglet')
  expect((await (await request.get('/api/state')).json()).correct).toBe(0)
  await other.close()
})

test('reset asks in the app and updates the journey', async ({ page }) => {
  await page.getByRole('button', { name: 'Révéler la réponse' }).click()
  await page.getByRole('button', { name: 'Bien retenu' }).click()
  await expect(page.locator('.session-summary')).toContainText('1')
  await page.getByRole('button', { name: 'Paramètres', exact: true }).click()
  await page.getByRole('button', { name: 'Réinitialiser la progression' }).click()
  await expect(page.getByRole('heading', { name: 'Une nouvelle page ?' })).toBeVisible()
  await page.getByRole('button', { name: 'Recommencer', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.navigation-position')).toContainText('01')
  await page.screenshot({ path: '/tmp/quizlet-web-desktop.png', fullPage: true })
})
